name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: build samples and apps
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
    - run: |
        pushd samples
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
        pushd apps/OboeTester
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
        pushd apps/fxlab
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
